[package]
name = "evdev"
version = "0.9.3"
authors = ["Corey Richardson <corey@octayn.net>"]
description = "evdev interface for Linux"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/cmr/evdev"
documentation = "https://docs.rs/evdev"

[dependencies]
ioctl = "0.3.3"
bitflags = "0.8.2"
errno = "0.2.3"
libc = "0.2.22"
fixedbitset = "0.1.6"
num = "0.1.37"

[features]
unstable = []
